name: SinkBans
version: ${project.version}
description: Ban Players!
author: Trojaner
website: http://static-interface.de
main: de.static_interface.sinkbans.SinkBans
depend: [SinkLibrary]

commands:
  ban:
    description: Allows to ban players
    usage: "/<command> [player} <reason>"
    permission: sinkbans.ban
    aliases: bann

  banip:
    description: Allows to ban ips
    usage: "/<command> [ip]"
    permission: sinkbans.ban

  isbanned:
    description: Allows to see why players are banned
    usage: "/<command> [player/ip]"
    permission: sinkbans.isbanned

  tempban:
    description: Allows to tempban players
    usage: "/<command> [player] [time]"
    permission: sinkbans.tempban

  unban:
    description: Allows to unban players
    usage: "/<command> [player]"
    permission: sinkbans.ban
    aliases: pardon

  unbanip:
    description: Allows to unban ips
    usage: "/<command> [ip]"
    permission: sinkbans.ban
    aliases: pardonip

  allowmultiaccount:
    description: Allows MultiAccount Usage
    usage: "/<command> <playername>"
    permission: sinkbans.allowmultiaccount
    aliases: amc

  bdebug:
    description: Debug
    usage: "/<command> <ip>"
    permission: sinkbans.ban

  banrequest:
    description: Request a ban
    aliases: banr
    permission: sinkbans.banrequest

permissions:
  sinkbans.*:
    description: Allows access to all ban commands
    default: op
    children:
      sinkbans.ban: true
      sinkbans.tempban: true
      sinkbans.isbanned: true
      sinkbans.allowmultiaccount: true
      sinkbans.notification: true
      sinkbans.banrequest: true

  sinkbans.ban:
    description: Allows to ban players
    default: op

  sinkbans.tempban:
    description: Allows to temp ban players
    default: op

  sinkbans.banrequest:
    description: Allows to temp ban players
    default: op

  sinkbans.isbanned:
    description: Allows to use the isBanned command
    default: true

  sinkbans.allowmultiaccount:
    description: Allows to use the allowmultiaccount command
    default: op

  sinkbans.notification:
    description: Allows to receive messages if someone is trying to join when banned
    default: op

  sinkbans.banrequestnotification:
    default: op

  sinkbans.banrequestacceptednotification:
    default: op